[package]
name = "fake_youki"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
nix = "0.21.0"
rand = "0.8.3"
